Add loginUser() helper method to Panther client
symfony/panther pull request #574
Opened 2022-10-07 11:31 UTC by plotbox-io

Please see [here](https://github.com/symfony/panther/issues/283) for discussion context

When doing E2E testing, it is common to need to login a user to perform certain actions. We often don't care about the login process for 99% of our tests, but we must still perform the steps each time. This can add unneccesary time and complexity onto the tests that could be avoided if only we had a way to simulate logins.

It would be nice to have a helper function named loginUser() similar to the [Application Test](https://symfony.com/doc/current/testing.html#application-tests) client. However, as we are doing E2E testing, we know that there is an added complexity of the environment settings of the alternate webserver (specifically how it handles session data). So, to solve this, we can pass SessionStorageInterface and firewallContext as arguments (but with sensisble defaults so they could be omitted in most cases).

Example of calling code would be:
```
$panther->logInUser(
    $user,
    new MockFileSessionStorage('/app/var/cache/panther/sessions'),
    'main'
);
```

Or simple (for most cases)

```
$panther->logInUser($user);
```

Have tested this approach (in userland code) and is working well for me. Was suggested in the discussion that I raise a PR for integration to Panther library code so here it is for your consideration. Please let me know if you need anything more from me.

Richard.

2023-01-10 08:09 UTC, shadydealer commented
@plotbox-io
Some apps would require a token other than a `UsernamePasswordToken`, could you make it an optional parameter instead?

Also wondering if this PR is even being considered?

2023-01-10 21:04 UTC, Bilge commented
The sheer number of assumptions baked into this is truly staggering.

2023-01-10 21:47 UTC, dunglas requested changes
I'm not fond of the general approach. This will break in many cases (Panther on the host, the Symfony app in a Docker container). Also, this creates a hard coupling between Panther (the library) and the full-stack Symfony framework.

Couldn't we try an alternative approach like trying to log the user using HTTP Basic or some other kind of standard approach instead?

2023-01-10 21:47 UTC, dunglas commented on src/Client.php
> +        $this->request('GET', '/');
It would be nice to be able to prevent this, at least if WebDriver is already initialized.

2023-01-10 21:47 UTC, dunglas commented on src/Client.php
> +            $sessionStorage = new MockFileSessionStorage('/app/var/cache/panther/sessions');
This should something like `tempnam(sys_get_temp_dir(), 'panther-sessions');` instead. This hardcoded directory may not be writable.

2023-01-12 01:52 UTC, arderyp commented
I'm interested in other approaches if people have clever ideas. Auth is an extremely common use case, so some sort of panther support for it would be cool

2023-01-12 07:10 UTC, dunglas commented
HTTP Basic?

2023-01-12 08:31 UTC, shadydealer commented
We use form login, accross all of our apps, so I don't think HTTP Basic would be of much use to us, unfortunately. 

I'm open to ideas on how to reduce the number of assumptions and how to decouple it from  the Symfony framework. If you look at the discussion in https://github.com/symfony/panther/issues/283 you'll see that the code was directly taken from the symfony testing framework, with a little modification, because, the perfect situation for me would be to have to only change `WebTestCase` to `PantherTestCase` and then use `static::createPantherClient()` where needed, making the transition from a WebTestCase to a PantherTestCase as seemless as possible.

Maybe the `loginUser` method could detect whether the project is using the Symfony framework or not, and behave differently depending on the result? Like, HTTP Basic for projects which aren't using Symfony and something along the lines of the code in the PR?

2023-01-12 20:59 UTC, dunglas commented
You could enable HTTP Basic only for the `panther` env. Or (or in addition), we could provide a helper to submit the standard Symfony login form using HTTP?

2023-01-14 18:43 UTC, arderyp commented
I'm also not keen on basic auth.  My actual site doesn't use it, and I want my tests to behave as closely to my live site as possible, including running through my real auth mechanism.

I think _allowing_ basic auth is fine, letting the implementer decide.  But forcing it doesn't seem appealing.

2023-01-14 22:41 UTC, dunglas commented
@arderyp that's the plan. You can already plug your custom auth logic if needed.

2024-06-26 18:50 UTC, antoniovj1 commented
@plotbox-io Do you need some help with this?

2024-07-01 12:56 UTC, closed without merging

2024-07-02 21:04 UTC, arderyp commented
Doesn't this issue remain, despite the original reporter not caring anymore? Should we reopen?

2024-07-03 06:52 UTC, antoniovj1 commented
@arderyp I think that @plotbox-io has closed this because it's his pull request, but yes, the issue remains. Should we use this MR or should we open an independent issue?

2024-07-03 15:05 UTC, arderyp commented
I suppose we could open a new one