feat: add PANTHER_REDUCED_MOTION to limit animations
symfony/panther pull request #651
Opened 2024-12-10 15:32 UTC by Jean-Beru

This PR add a `PANTHER_REDUCED_MOTION` environment variable to set the `prefers-reduced-motion` CSS media feature to `reduce`.

It could be useful to limit "flaky" tests which result in a `Facebook\WebDriver\Exception\ElementClickInterceptedException: Element <XXX> is not clickable at point (XXX, YYY) because another element XXX obscures it` exception because an animation is still in progress.

This CSS media feature is already supported by [Bootstrap](https://getbootstrap.com/docs/4.1/getting-started/accessibility/#reduced-motion) or the french [DSFR](https://github.com/GouvernementFR/dsfr).

2025-01-07 10:33 UTC, dunglas requested changes
Good idea! We should even enable this by default.

2025-01-07 10:33 UTC, dunglas commented on src/ProcessManager/ChromeManager.php
> +        if ($_SERVER['PANTHER_REDUCED_MOTION'] ?? false) {
```suggestion
        if (filter_var($_SERVER['PANTHER_REDUCED_MOTION'] ?? true, \FILTER_VALIDATE_BOOLEAN)) {
```

(see #632)

2025-01-07 10:33 UTC, dunglas commented on src/ProcessManager/FirefoxManager.php
> +        if ($_SERVER['PANTHER_REDUCED_MOTION'] ?? false) {
```suggestion
        if (filter_var($_SERVER['PANTHER_REDUCED_MOTION'] ?? true, \FILTER_VALIDATE_BOOLEAN)) {
```

2025-01-07 17:29 UTC, Jean-Beru commented
> Good idea! We should even enable this by default.

I totally agree :slightly_smiling_face:

2025-01-08 09:46 UTC, dunglas commented
Maybe make this config the default and introduce a `PANTHER_NO_REDUCED_MOTION` to disable it then?

2025-01-08 14:54 UTC, Jean-Beru commented
It make sense with `PANTHER_NO_HEADLESS` :+1: 

I also added a test (and fixed a bug spotted by it).

2025-01-08 15:39 UTC, dunglas approved these changes

2025-01-08 15:39 UTC, dunglas commented on src/ProcessManager/ChromeManager.php
> +        // Prefer reduced motion, see https://developer.mozilla.org/fr/docs/Web/CSS/@media/prefers-reduced-motion
```suggestion
        // Prefer reduced motion, see https://developer.mozilla.org/docs/Web/CSS/@media/prefers-reduced-motion
```

2025-01-08 15:40 UTC, dunglas commented
Thank you!

2025-01-08 15:41 UTC, Jean-Beru commented
@dunglas FYI, I'm trying to understand why https://github.com/symfony/panther/actions/runs/12673280007/job/35319306027?pr=651 is failing

2025-01-08 15:42 UTC, merged

2025-01-08 15:42 UTC, dunglas commented
Thanks!